title: The Blogging Site.
author: Anusha 
email: anushat237@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  You will find all the new and interesting activities taking place in the technical department.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
